# Template for setting up the Ubuntu build environment and building Xournal++ on
# Ubuntu

steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y gcc-8 g++-8 cmake ninja-build libcppunit-dev libgtk-3-dev libpoppler-glib-dev portaudio19-dev libsndfile-dev liblua5.3-dev libzip-dev lsb-release gettext
      # Install libzip5 on Ubuntu >= 20.04
      if [[ "$(lsb_release -a 2>/dev/null | grep Release | cut -f 2)" == "20.04" ]]; then
        sudo apt-get install libzip5
        (cd /usr/lib/x86_64-linux-gnu && sudo ln -s libzip.so -f libzip.so.5)
      fi
      g++ --version
    displayName: 'Install dependencies'
